package com.openai.companion.kmp

/** Shape generated by UniFFI from harness.udl. */
interface RustToolProvider {
    suspend fun getTools(): List<McpTool>
    suspend fun callTool(name: String, argumentsJson: String): String
}

data class McpTool(
    val name: String,
    val description: String,
    val inputSchemaJson: String,
)

/** Synchronous UniFFI callback over the manager's last refreshed snapshot. */
class McpToolProvider(private val manager: McpServerManager) : RustToolProvider {
    /** Reads the current aggregate so server attach/detach is immediately visible to Rust. */
    override suspend fun getTools(): List<McpTool> = manager.tools().map {
            McpTool(it.name, it.description, it.inputSchemaJson)
    }

    override suspend fun callTool(name: String, argumentsJson: String): String =
        manager.callTool(name, argumentsJson)
}
