package com.openai.companion.kmp

import com.openai.companion.kmp.device.DeviceToolConnection

import kotlinx.coroutines.CancellationException

/** Shape generated by UniFFI from harness.udl. */
interface RustToolProvider {
    suspend fun getTools(): List<McpTool>
    suspend fun callTool(name: String, argumentsJson: String, executionContext: String = "foreground"): McpCallResult
}

data class McpTool(
    val name: String,
    val description: String,
    val inputSchemaJson: String,
    val policy: ToolPolicy = ToolPolicy(),
)

/** Async UniFFI callback over the manager's current aggregate snapshot. */
class McpToolProvider(
    private val manager: McpServerManager,
    private val approve: suspend (String, String) -> Boolean,
    private val remoteApprovalName: (String) -> String,
) : RustToolProvider {
    constructor(manager: McpServerManager, approve: suspend (String, String) -> Boolean) :
        this(manager, approve, { it })
    /** Reads the current aggregate so server attach/detach is immediately visible to Rust. */
    override suspend fun getTools(): List<McpTool> = try {
        manager.tools().map { it.toHarnessTool() }
    } catch (error: ToolExecutionException) {
        throw error
    } catch (error: CancellationException) {
        throw error
    } catch (error: Throwable) {
        throw ToolExecutionException(
            ToolExecutionErrorCode.NETWORK_UNREACHABLE,
            error.message.orEmpty(),
            error,
        )
    }

    override suspend fun callTool(name: String, argumentsJson: String, executionContext: String): McpCallResult = try {
        val ticket = manager.prepareToolCall(name)
        val policy = ticket.tool.policy
        if (!policy.valid() || executionContext !in setOf("foreground", "background") ||
            executionContext == "background" && !policy.allowsBackgroundRead()) {
            throw ToolExecutionException(ToolExecutionErrorCode.PERMISSION_DENIED, "Host policy forbids this execution context")
        }
        val approvalName = if (ticket.connection is DeviceToolConnection) "本机 · $name（结果供当前模型处理）" else remoteApprovalName(name)
        if (policy.requiresApproval && !approve(approvalName, argumentsJson)) {
            throw ToolExecutionException(
                ToolExecutionErrorCode.PERMISSION_DENIED,
                "用户未批准 MCP 工具调用：$name",
            )
        }
        manager.callTool(ticket, argumentsJson)
    } catch (error: ToolExecutionException) {
        throw error
    } catch (error: CancellationException) {
        throw error
    } catch (error: IllegalArgumentException) {
        throw ToolExecutionException(
            ToolExecutionErrorCode.INVALID_ARGUMENTS,
            error.message.orEmpty(),
            error,
        )
    } catch (error: Throwable) {
        throw ToolExecutionException(
            ToolExecutionErrorCode.UNKNOWN,
            error.message.orEmpty(),
            error,
        )
    }
}
